---
-
  connection: local
  hosts: all
  tasks:
    -
      action:
        group: SeGB
        image: ami-9e2f0988
        instance_tags:
          OWNER: GB
          name: NEWGB
        instance_type: t2.micro
        key_name: Containers
        module: ec2
        region: us-east-1
        state: present
        vpc_subnet_id: subnet-ea512b8f
      name: "create ec2 instance"